services:
  api:
    build:
      context: .
      dockerfile: recipevault.API/Dockerfile
      target: final
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:${APP_PORT}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${APP_PORT}/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - migrations

  migrations:
    build:
      context: .
      dockerfile: recipevault.API/Dockerfile
      target: build
    command: ['dotnet', 'ef', 'database', 'update']
    restart: no
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}

volumes:
  recipevault_db:
