# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
version: '3.8'

services:
  api:
    image: recipevault-api
    build:
      context: ../..
      dockerfile: ./recipevault.API/Dockerfile
      target: build
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000;http://+
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=postgres;Username=postgres;Password=postgres
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=cert
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      # - /https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
      - ./recipevault.API:/app
    ports:
      - 5000:5000
      - 5001:80
    command: sh -c "dotnet dev-certs https -ep /https/aspnetcert.pfx -p cert && dotnet watch run --no-launch-profile || tail -f /dev/null"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8880:80
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
